Flipping a coin in Python

In [1]:
from scipy.stats import bernoulli
bernoulli.rvs(p=0.5, size=1)

array([0])

Another run

In [3]:
bernoulli.rvs(p=0.5, size=1)

array([1])

Changing size parameter to flip more coins

In [4]:
bernoulli.rvs(p=0.5, size=10)

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1])

How many heads? 

In [8]:
sum(bernoulli.rvs(p=0.5, size=10))

6

The binomial distribution is a probability distribution that describes the number of successes in a fixed number of independent Bernoulli trials (experiments with only two possible outcomes, like success/failure or yes/no).

In [9]:
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=1)

array([4])

In [10]:
binom.rvs(n=10, p=0.5, size=10)

array([6, 3, 6, 6, 3, 6, 6, 4, 5, 6])

In [11]:
binom.rvs(n=10, p=0.3, size=10)

array([2, 3, 5, 1, 1, 2, 4, 1, 1, 2])

Random seed generation

random_state parameter for rvs() func

alternative use numpy.random.seed()

In [12]:
binom.rvs(n=10, p=0.5, size=1, random_state = 42)

array([4])

In [14]:
import numpy as np
np.random.seed(42)

binom.rvs(n=10, p=0.5, size=1)

array([4])